copy c:\temp\Components.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\GroupKits.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Shocks.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\TiresAndTubes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Wheels.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Accessories.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Basso_FrontSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Basso_FullSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Basso_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BikeHard_HybridBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BikeHard_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Carrera_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Colnago_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Dahon_FoldingBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Dahon_HybridBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\FujiUSA_ChildrensBikes-16-20.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\FujiUSA_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\GT_BMXFreestyle_Racing.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\GT_BMXJumpingBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\GT_FrontSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\GT_FullSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Ironhorse_ChildrensBikes-16-20.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Ironhorse_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Kestrel_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\KHS_FoldingBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Look_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Marin_FrontSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Marin_FullSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Marin_HybridBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Marin_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Marin_SportComfortBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Mongoose_BMXFreestyle_Racing.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Mongoose_BMXJumpingBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Mongoose_ChildrensBikes-16-20.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Mongoose_FrontSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Mongoose_FullSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Olmo_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Pinarello_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Raleigh_RoadBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Schwinn_ChildrensBikes-16-20.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\TomacUSA_FullSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\WorksmanTradingCorp._SportComfortBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\YetiCycles_FullSuspensionBikes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BarEnds.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BottomBrackets.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Brakes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Brakes-Disc.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Cassettes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Chains.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Cranksets.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\FrontDerailleur.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\HandlebarTape_Grips.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Handlebars.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Headsets.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Hubs.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\MiscellaneousComponents.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\RearDerailleur.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Seatposts.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Shifter_Levers.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Shifters.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Stems.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\MountainKits.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\RoadGroups.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\RoadKits.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\CliplessPedals.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\RegularPedals.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\ShockAccessories.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Shocks_Forks.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\ATBTires.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BMXTires.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\RoadTires.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\TireTools.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Tubes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BMXWheels.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\MountainWheels.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\RoadWheels.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Bib(shortAndtight).htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BodyArmor.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Eyewear.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Gloves.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Hats.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Jackets.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Jerseys.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Shorts.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Socks.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Tights.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\WinterClothingAccessories.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Adidas_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Adidas_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Airwalk_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\AnswerManitou_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Cannondale_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Diadora_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Diadora_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\LouisGarneau_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\LouisGarneau_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Nike_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Nike_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Northwave_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Northwave_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\PearlIzumi_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\PearlIzumi_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\ProfileDesigns_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Shimano_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Shimano_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\SIDI_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\SIDI_RoadShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\SIXSIXONE_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Specialized_MountainShoes.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Food.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Bags.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BicycleFenders.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BikeRacks.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BMXAccessories.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\LightSets.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Mirrors.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Pumps.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Babyseats.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\BicycleStorage.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\CarCarriers.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\CycleComputers.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\HeartRateMonitors.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Joggers.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Trailers.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Lubricants.htm		v:\root\new.bicyclebuys.com\docs\HTML
copy c:\temp\Hydration_BottleCages.htm v:\root\new.bicyclebuys.com\docs\HTML\Hydration_EnergyFoodandDrinks.htm
copy c:\temp\Hydration_BottleCages.htm v:\root\new.bicyclebuys.com\docs\HTML\HydrationandBottleCages.htm
copy c:\temp\CycleComputers.htm v:\root\new.bicyclebuys.com\docs\HTML\CycleComputers_HeartRateMonitors.htm
copy c:\temp\CycleComputers.htm v:\root\new.bicyclebuys.com\docs\HTML\CycleComputers_HeartRateMonitors.htm
copy c:\temp\Seats.htm  v:\root\new.bicyclebuys.com\docs\HTML\Saddles.htm

copy c:\temp\Handlebars.htm v:\root\new.bicyclebuys.com\docs\HTML\BikeParts_AeroBars.htm