<% Dim vSubcatWDSD
Set vSubcatWDSD = Server.CreateObject("Scripting.Dictionary")
vSubcatWDSD.Item("43") = "Full Suspension Bikes"
vSubcatWDSD.Item("45") = "Front Suspension Bikes"
vSubcatWDSD.Item("46") = "Hybrid Bikes"
vSubcatWDSD.Item("50") = "BMX Jumping  Bikes"
vSubcatWDSD.Item("51") = "BMX Freestyle/Racing"
vSubcatWDSD.Item("54") = "Road Bikes"
vSubcatWDSD.Item("95") = "Sport Comfort Bikes"
vSubcatWDSD.Item("96") = "Children's Bikes- 16&quot;-20&quot;"
vSubcatWDSD.Item("97") = "Bicycle Tool Sets"
vSubcatWDSD.Item("98") = "Drivetrain Tools"
vSubcatWDSD.Item("99") = "Brake Tools"
vSubcatWDSD.Item("100") = "Headset / Bottom Bracket Tools"
vSubcatWDSD.Item("101") = "Wheels / Rims Tools"
vSubcatWDSD.Item("102") = "Road Shoes"
vSubcatWDSD.Item("103") = "Mountain Shoes"
vSubcatWDSD.Item("104") = "Folding Bikes"
vSubcatWDSD.Item("105") = "Cruiser Bikes"
vSubcatWDSD.Item("200") = "BMX Helmets"
vSubcatWDSD.Item("203") = "Reflective Wear"
vSubcatWDSD.Item("210") = "Energy Food and Drinks"
%>
