<% Dim vWebNoteSD
Set vWebNoteSD = Server.CreateObject("Scripting.Dictionary")
vWebNoteSD.Item("1") = "No Note"
vWebNoteSD.Item("2") = "Limited Time Offer, Limited Quantities Available."
vWebNoteSD.Item("3") = "In Store Sales Only. Call for Details."
vWebNoteSD.Item("4") = "** Call For Manager's Back-Pocket Special Price!"
vWebNoteSD.Item("5") = "** New Low Price!!"
vWebNoteSD.Item("6") = "** Introductory Price!!"
vWebNoteSD.Item("7") = "** We Are Discontinuing This Item, Clearance Price!!"
vWebNoteSD.Item("8") = "**Pre-Book Now to Assure Delivery.  Call for Delivery Schedule. 1- 888 4-Bike Buy!"
vWebNoteSD.Item("9") = "** Will Price Match Item.  Call 1-888-4-Bike Buy!(1-888-424-5328)"
vWebNoteSD.Item("10") = "*This Month's Special.  Limited to Stock on Hand!*"
vWebNoteSD.Item("11") = "**Shimano Sale For Next 10 Days Only!!**"
vWebNoteSD.Item("12") = "**Free Profile Bottle And Computer Mount Valued at $25.00!!**"
vWebNoteSD.Item("13") = "Tour De France Special.  Limited time only!"
vWebNoteSD.Item("14") = "Look at the Storewide Special.  This discount will be reflected at the end of the checkout process in the shopping cart as a discount to your whole order.  Thank You."
vWebNoteSD.Item("15") = "Rebate will be applied during checkout."
vWebNoteSD.Item("16") = "Winter Gift with every Kurt Kinetic, CatEye Strada Cadence Cycle Computer (Value $ 50.00)."
vWebNoteSD.Item("17") = "Call For Our Unadvertised Best Price!"
vWebNoteSD.Item("18") = "Enjoy the Holiday season with this Special Holiday pricing!"
vWebNoteSD.Item("19") = "We will upgrade the shipping to Next Day at no extra charge.  Select Regular Ground service at Checkout."
vWebNoteSD.Item("20") = "YETI SALE!!! Prices good to stock on hand till August 31st 2007.  Save now on this once in a year SALE!!!"
vWebNoteSD.Item("21") = "Blackburn Trainers on Sale during the month of August.  Limited to quantities on hand."
vWebNoteSD.Item("23") = "Call about our Special on early 2007 Enduro Kits with  Avid Juicy 5 Brakes and Alloy Triangle 575's.  Save big Bucks!!"
vWebNoteSD.Item("24") = "Bell And Giro Limited Time Sale.  Prices good till 08/15/07 while supplies last!"
vWebNoteSD.Item("25") = "Shimano Ultegra 10/speed Double and Triple Blow Out Sale!  Prices good while supplies last for the month of August!"
%>
